/*
 * This source file was generated by the Gradle 'init' task
 */
package demo.rxjava;

import org.junit.jupiter.api.Test;
import spock.lang.Specification;
import spock.lang.Unroll;
import static org.junit.jupiter.api.Assertions.*;


class CalculatorSpec extends Specification {

    def "add two numbers"() {
        given: "a calculator"
        def calculator = new Calculator()
        println ">>> 'given' 块执行完毕：计算器已创建"


        when: "we add two numbers"
        def result = calculator.add(1, 2)
        println ">>> 'when' 块执行完毕：计算结果 = $result"

        then: "the result is 3"
        result == 3
        println ">>> 'then' 块执行完毕：结果验证 = $result == 3"
    }

    @Unroll
    def "add #a and #b"() {
        given: "a calculator"
        def calculator = new Calculator()
        println ">>> 'given' 块执行完毕：计算器已创建"

        when: "we add two numbers"
        def result = calculator.add(a, b)
        println ">>> 'when' 块执行完毕：计算结果 = $result"

        then: "the result is #result"
        result == expected
        println ">>> 'then' 块执行完毕：结果验证 = $result == $expected"

        where:
        a | b | expected
        1 | 2 | 3
        2 | 3 | 5
        3 | 4 | 7
        4 | 5 | 9
        5 | 6 | 11
    }

}