"""Initial migration

Revision ID: da45316908ca
Revises: 
Create Date: 2025-09-28 17:45:13.397169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da45316908ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='oauth2'
    )
    op.create_index(op.f('ix_oauth2_app_user_uuid'), 'app_user', ['uuid'], unique=True, schema='oauth2')
    op.create_table('app_authentication',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=20), nullable=False),
    sa.Column('credential', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['oauth2.app_user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='oauth2'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_authentication', schema='oauth2')
    op.drop_index(op.f('ix_oauth2_app_user_uuid'), table_name='app_user', schema='oauth2')
    op.drop_table('app_user', schema='oauth2')
    # ### end Alembic commands ###
