/*
 * This source file was generated by the Gradle 'init' task
 */
package demo.rxjava;

// src/main/java/HelloWorld.java

import lombok.extern.slf4j.Slf4j;

import java.util.concurrent.TimeUnit;

import io.reactivex.rxjava3.core.Observable;
import io.reactivex.rxjava3.disposables.Disposable;
import io.reactivex.rxjava3.schedulers.Schedulers;
import io.reactivex.rxjava3.observables.ConnectableObservable;

@Slf4j
public class App2 {

    private static void testThread() {
        log.info("Test thread");
        Observable.create(subscriber -> {
            Runnable runnable = () -> {
                log.info("Create Observable");
                subscriber.onNext(1);
                log.info("Emitting 2");
                subscriber.onNext(2);
                log.info("Emitting 3");
                subscriber.onNext(3);
                log.info("Sequence complete");
                subscriber.onComplete();
            };
            new Thread(runnable).start();
        }).subscribe(i -> log.info("Received: " + i));

        log.info("Subscription complete");
    }

    private static void testTimerInterval() throws InterruptedException {

        Observable.timer(1, TimeUnit.SECONDS)
                .subscribe(i -> log.info("timer Received: " + i));

        Observable.interval(1, TimeUnit.SECONDS)
                .subscribe(i -> log.info("Received: " + i));
        Thread.sleep(10000);

        log.info("Subscription complete");
    }

    private static void testHotObservable() throws InterruptedException {
        // 原始的 Cold Observable
        Observable<Long> coldSource = Observable.interval(1, TimeUnit.SECONDS);

        // 1. 转换：使用 publish() 得到一个 ConnectableObservable
        log.info("广播站已建好 (publish)...");
        ConnectableObservable<Long> hotBroadcast = coldSource.publish();

        // 2. 订阅：第一个听众调好频道
        log.info("订阅者 1 正在收听...");
        hotBroadcast.subscribe(val -> log.info("订阅者 1 收到: " + val));

        // 3. 连接：按下总开关，广播开始！
        log.info("按下总开关 (connect)...");
        Disposable connection = hotBroadcast.connect(); // connect() 会返回一个 Disposable

        // 等待3秒
        Thread.sleep(3500);

        // 此时，第二个听众中途加入
        log.info("订阅者 2 中途加入...");
        hotBroadcast.subscribe(val -> log.info("订阅者 2 收到: " + val));

        // 再等待3秒
        Thread.sleep(3000);

        // 关闭总开关，停止广播
        log.info("关闭总开关...");
        connection.dispose();
        log.info("广播已停止。");

        Thread.sleep(2000); // 即使源头停止了，也不会再有输出了
    }

    private static void testScheduler() throws InterruptedException {

        log.info("程序开始，当前线程: " + Thread.currentThread().getName());

        Observable.just("A", "B", "C")
                // 1. 指定源头和 map 在 IO 线程池中执行
                .subscribeOn(Schedulers.io())
                .map(s -> {
                    log.info("map 操作，当前线程: " + Thread.currentThread().getName());
                    return s + "1";
                })
                // 2. 指定下游的 Observer 在 computation 线程池中执行
                .observeOn(Schedulers.computation())
                .subscribe(s -> {
                    log.info("onNext 收到数据: " + s + "，当前线程: " + Thread.currentThread().getName());
                });

        log.info("程序结束，当前线程: " + Thread.currentThread().getName());

        // 等待异步任务完成，否则 main 线程会直接退出
        Thread.sleep(1000);
    }

    private static void testMap() {

        Observable.just(8, 9, 10)
                .doOnNext(i -> log.info("A: init: " + i))
                .filter(i -> i % 3 > 0)
                .doOnNext(i -> log.info("B: filter: " + i))
                .map(i -> "#" + i * 10)
                .doOnNext(i -> log.info("C: map: " + i))
                .filter(s -> s.length() < 4)
                .subscribe(s -> log.info("D: filter: " + s));
    }

    private static void testDelay() throws InterruptedException {
        Observable.just(10L, 9L, 8L)
                .doOnNext(i -> log.info("A: init: " + i))
                .delay(1, TimeUnit.SECONDS)
                .doOnNext(i -> log.info("B: delay: " + i))
                .subscribe(s -> log.info("C: " + s));
        Thread.sleep(10000);
    }

    private static void testDynamicDelay() throws InterruptedException {

        Observable.just("AAAAA", "BBB", "C")
                .doOnNext(s -> log.info("源头发射 " + s + " at: " + System.currentTimeMillis()))
                .delay(item -> {
                    // 这是我们的 itemDelay 选择器函数
                    // 它为每个 item 创建一个独立的 timer
                    log.info("  -> 为 '" + item + "' 创建一个 " + item.length() + " 秒的延迟信号");
                    return Observable.timer(item.length(), TimeUnit.SECONDS);
                })
                .subscribe(
                        item -> log.info("下游收到 " + item + " at: " + System.currentTimeMillis()),
                        Throwable::printStackTrace,
                        () -> log.info("下游 onComplete"));

        Thread.sleep(10000);
    }

    private static void testFlatMapConcurrent() throws InterruptedException {

        // --- 场景 1: 不控制并发 ---
        log.info("--- 场景 1: 不控制并发的 flatMap ---");
        Observable.range(1, 10)
                .flatMap(item -> longRunningTask(item))
                .subscribe(result -> log.info("结果: " + result));

        Thread.sleep(6000); // 等待任务完成

        // --- 场景 2: 控制并发数为 3 ---
        log.info("\\n\\n--- 场景 2: flatMap(maxConcurrency = 3) ---");
        Observable.range(1, 10)
                .flatMap(item -> longRunningTask(item), 3) // **关键在这里**
                .subscribe(result -> log.info("结果: " + result));

        Thread.sleep(10000); // 等待任务完成
    }

    private static Observable<String> longRunningTask(int item) {
        return Observable.fromCallable(() -> {
            log.info("--> 开始处理任务: " + item);
            Thread.sleep(2000); // 模拟耗时
            log.info("<-- 任务处理完成: " + item);
            return "任务 " + item + " 的结果";
        }).subscribeOn(Schedulers.io()); // 让任务在后台线程执行
    }

    private static void testCompose() {
        Observable.just("data1", "data2", "data3")
                .doOnNext(data -> log.info("Original thread: " + Thread.currentThread().getName()))
                .compose(SchedulersTransformer.applySchedulers()) // <-- 在这里使用
                .doOnNext(data -> log.info("Transformed thread: " + Thread.currentThread().getName()))
                .subscribe(
                        result -> log.info("Result: " + result),
                        Throwable::printStackTrace,
                        () -> log.info("Done"));

        // 等待异步操作完成
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    private static void testBlock() {
        Observable<String> source = Observable.just("Alpha", "Beta", "Gamma").doOnNext(x -> log.info(x));

        // 1. 获取第一个元素
        // 线程会在这里阻塞，直到 "Alpha" 被发射出来
        String first = source.blockingFirst();
        log.info("blockingFirst(): " + first); // 输出: blockingFirst(): Alpha

        // 2. 获取最后一个元素
        // 线程会在这里阻塞，直到整个 Observable 完成
        String last = source.blockingLast();
        log.info("blockingLast(): " + last); // 输出: blockingLast(): Gamma

        // 3. 遍历所有元素
        log.info("blockingIterable():");
        Iterable<String> allItems = source.blockingIterable();
        for (String item : allItems) {
            // for循环的每次迭代都会等待下一个元素
            log.info("- " + item);
        }
    }

    public static void main(String[] args) throws InterruptedException {

        testBlock();
        // testHotObservable();
        // testTimerInterval();
        // testFlatMapConcurrent();
    }

}
